apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointee-api
  labels:
    app: appointee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointee-api
  template:
    metadata:
      labels:
        app: appointee-api
    spec:
      containers:
      - name: appointee-api
        image: registry.digitalocean.com/docr-appointee/api:latest
        env:
        - name: GoogleAPI__Key
          value: "AIzaSyCkSKM3cIARzBXU_VYFCAx0dbNIABniQoI"
        - name: WebUrl
          value: "https://appoint.ee"
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: appointee-api-service
spec:
  selector:
    app: appointee-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer