name: AppointeeWeb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Build Docker image
      run: docker build -t api .

    - name: Tag Docker image
      run: docker tag api registry.digitalocean.com/docr/api:latest

    - name: Push Docker image
      run: docker push registry.digitalocean.com/docr/api:latest
