name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/rich-compiler-425212-b5/appointee/api:latest .
          docker push europe-west1-docker.pkg.dev/rich-compiler-425212-b5/appointee/api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials [YOUR_CLUSTER_NAME] --zone europe-west1 --project rich-compiler-425212-b5

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./deployment.yaml
