# pipeline.yaml

# Pipeline configuration to build Docker image, push to Artifact Registry, and deploy to GKE

# Define the pipeline
pipeline:
  name: appointee-api
  # Specify the triggers for the pipeline, e.g., on push to main branch
  trigger:
    branch:
      - main

  # Define the jobs that make up this pipeline
  jobs:
    - name: build-and-push-container
      # This job builds Docker image from Dockerfile and pushes to Google Artifact Registry
      steps:
        - name: checkout-repo
          # Checkout the GitHub repository
          image: alpine/git
          commands:
            - git clone https://github.com/appoint-ee/api.git ./source

        - name: build-container
          # Build Docker image using Dockerfile in the repository
          image: docker:19.03.12
          commands:
            - cd ./blob/main/Dockerfile  # Adjust path to your Dockerfile
            - docker build -t europe-west1-docker.pkg.dev/rich-compiler-425212-b5/appointee/api:latest .
            - docker push europe-west1-docker.pkg.dev/rich-compiler-425212-b5/appointee/api:latest:latest

    - name: deploy-to-gke
      # This job deploys the Kubernetes manifest to Google Kubernetes Engine
      steps:
        - name: deploy
          image: google/cloud-sdk:latest
          env:
            - GOOGLE_APPLICATION_CREDENTIALS: ${{secret:googlecredentials}}
          commands:
            - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
            - gcloud config set project rich-compiler-425212-b5
            - gcloud config set compute/zone europe-west1

            # Apply deployment.yaml to your Kubernetes cluster
            - kubectl apply -f ./deployment.yaml  # Adjust path to your deployment.yaml

# Specify the resources that may be used in the pipeline
resources:
  # Define the secrets needed in the pipeline
  secrets:
    - name: google-cloud-credentials
      type: gcpServiceAccount
      keyfile: base64stringofyourgcpkeyfile

# Define the configuration for the pipeline execution
configuration:
  # Specify the GCP project ID where your Artifact Registry and GKE cluster are located
  projectId: rich-compiler-425212-b5
